export { default as Dashboard } from './Dashboard'
export {default as VoteForm} from './vote/Form'
export { default as EditVote } from './vote/Edit'
export { default as AddVote } from './vote/Add'
export { default as ListVote } from './vote/ListVote'
export { default as Vote } from './vote/Vote'
export { default as AssetList } from './Asset/AssetList'
export { default as Proposal } from './Proposal/Proposal'
export { default as SettingDashboard } from './General/Dashboard'
export { default as Whitepaper } from './Whitepaper/Whitepaper'
