export const vote = {
    SET_ONE_QN_NO_VOTE_WEIGHTAGE: 'SET_ONE_QN_NO_VOTE_WEIGHTAGE',
    SET_ONE_QN_YES_VOTE_WEIGHTAGE: 'SET_ONE_QN_YES_VOTE_WEIGHTAGE',

    SET_TWO_QN_NO_VOTE_WEIGHTAGE: 'SET_TWO_QN_NO_VOTE_WEIGHTAGE',
    SET_TWO_QN_YES_VOTE_WEIGHTAGE: 'SET_TWO_QN_YES_VOTE_WEIGHTAGE',

    SET_THREE_QN_NO_VOTE_WEIGHTAGE: 'SET_THREE_QN_NO_VOTE_WEIGHTAGE',
    SET_THREE_QN_YES_VOTE_WEIGHTAGE: 'SET_THREE_QN_YES_VOTE_WEIGHTAGE',

    SET_FOUR_QN_NO_VOTE_WEIGHTAGE: 'SET_FOUR_QN_NO_VOTE_WEIGHTAGE',
    SET_FOUR_QN_YES_VOTE_WEIGHTAGE: 'SET_FOUR_QN_YES_VOTE_WEIGHTAGE',

    SET_FIVE_QN_NO_VOTE_WEIGHTAGE: 'SET_FIVE_QN_NO_VOTE_WEIGHTAGE',
    SET_FIVE_QN_YES_VOTE_WEIGHTAGE: 'SET_FIVE_QN_YES_VOTE_WEIGHTAGE',

    SET_ONE_QN_NO_VOTE_PCT: 'SET_ONE_QN_NO_VOTE_PCT',
    SET_ONE_QN_YES_VOTE_PCT: 'SET_ONE_QN_YES_VOTE_PCT',

    SET_TWO_QN_NO_VOTE_PCT: 'SET_TWO_QN_NO_VOTE_PCT',
    SET_TWO_QN_YES_VOTE_PCT: 'SET_TWO_QN_YES_VOTE_PCT',

    SET_THREE_QN_NO_VOTE_PCT: 'SET_THREE_QN_NO_VOTE_PCT',
    SET_THREE_QN_YES_VOTE_PCT: 'SET_THREE_QN_YES_VOTE_PCT',

    SET_FOUR_QN_NO_VOTE_PCT: 'SET_FOUR_QN_NO_VOTE_PCT',
    SET_FOUR_QN_YES_VOTE_PCT: 'SET_FOUR_QN_YES_VOTE_PCT',

    SET_FIVE_QN_NO_VOTE_PCT: 'SET_FIVE_QN_NO_VOTE_PCT',
    SET_FIVE_QN_YES_VOTE_PCT: 'SET_FIVE_QN_YES_VOTE_PCT'
};